services:
  flaskr:
    build: ./docker/flaskr
    image: meredith1771/meredith-deploy-playground:latest
    ports:
      - "3000:8000"
    restart: always
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"