services:
  flaskr:
    image: meredith1771/flaskr:latest
    build:
      dockerfile: ./docker/flaskr/Dockerfile
    restart: always
  nginx:
    image: meredith1771/nginx:latest
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
