services:
  nginx:
    image: meredith1771/nginx:latest
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--header", "Host: meredith-deploy-playground.co", "http://localhost:80/"]
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 2s
    restart: unless-stopped
  flaskr:
    image: meredith1771/flaskr:latest
    build:
      dockerfile: ./docker/flaskr/Dockerfile
    restart: unless-stopped
  redis:
    image: meredith1771/redis:8.0-M03-alpine3.21
    build:
      dockerfile: ./docker/redis/Dockerfile
    restart: unless-stopped
    ports:
      - "6379:6379"
