---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskr
  namespace: calico-system
  labels:
    app: flaskr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskr
  template:
    metadata:
      labels:
        app: flaskr
    spec:
      imagePullSecrets:
        - name: docker-login-credentials
      containers:
        - name: flaskr
          image: meredith1771/meredith-deploy-playground:pipelinev1
          ports:
            - containerPort: 8000
