# Buildkite assigns DOCKER_LOGIN_PASSWORD via an agent hook that runs at the beginning of every step assigning `password-env:`
# https://buildkite.com/docs/agent/v3/hooks#hook-locations-agent-hooks

steps:
  - label: "Build nginx web server"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    - docker-compose#v5.4.1:
        build: nginx
        push: nginx:meredith1771/nginx:latest

  - label: "Build flaskr app"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    - docker-compose#v5.4.1:
        build: flaskr
        push: "flaskr:meredith1771/meredith-deploy-playground:${BUILDKITE_COMMIT}"

  - wait

  - label: ":rocket: Start database"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    command: "bin/database.sh"

  - label: ":rocket: Deploy flaskr app"
    command: "bin/deploy.sh"
    env:
      DOCKER_IMAGE: "meredith1771/meredith-deploy-playground:${BUILDKITE_COMMIT}"

  - wait

  - label: "Configure nginx"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    command: "bin/nginx.sh"
