steps:
  - label: "Build"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    - docker-compose#v5.4.1:
        build: web
        push: web:meredith1771/meredith-deploy-playground:latest

  - wait

  - label: ":rocket: Deploy"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    - docker-compose#v5.4.1:
        # This is failing because it's running on the buildkite-agent instance, not the web server instance
        # I think I need to install the buildkite-agent on the web server and delete the buildkite-agent instance
        run: web