steps:
  - label: "Build nginx web server"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    - docker-compose#v5.4.1:
        build: nginx
        push: nginx:meredith1771/nginx:latest


  - label: "Build flaskr app"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    - docker-compose#v5.4.1:
        build: flaskr
        push: flaskr:meredith1771/meredith-deploy-playground:latest

  - wait

  - label: ":rocket: Deploy flaskr app"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    command: "bin/deploy.sh"

  - label: "Configure nginx"
    plugins:
    - docker-login#v3.0.0:
        username: meredith1771
        password-env: DOCKER_LOGIN_PASSWORD
    command: "bin/nginx.sh"
